# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build, Lint, Test and Run Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  check:

    runs-on: ubuntu-latest
    environment: "Workflow: tests"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install torch --no-cache-dir

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --statistics --ignore=E501,W605

    - name: Build python code
      run: |
        # Compile with py_compile / see if there are no errors
        sh bin/build.sh  

    - name: Perform python unit-tests and test run
      env:
        CONFIGURATION: ${{ secrets.CONFIGURATION }}
      run: |
        # Write a default configuration
        touch config.ini
        echo "$CONFIGURATION" > config.ini
        # Perform unit tests and run program
        #        mkdir -p /opt
        #        mkdir -p /opt/hostedtoolcache
        #        mkdir -p /opt/hostedtoolcache/python
        #        mkdir -p /opt/hostedtoolcache/python/3.10.11
        #        mkdir -p /opt/hostedtoolcache/python/3.10.11/x64
        #        mkdir -p /opt/hostedtoolcache/python/3.10.11/x64/lib
        #        mkdir -p /opt/hostedtoolcache/python/3.10.11/x64/lib/python3.10
        tree /opt/hostedtoolcache
        touch /opt/hostedtoolcache/python/3.10.11/x64/lib/python3.10/site-packages/.yolov7_qrdetvc7fummf.tmp
        python3 -c 'import qrdet; qrdet.QRDetector()'
        python3 _unit_tests.py
